# Generated by Django 5.2.4 on 2025-07-07 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alphabet', models.CharField(help_text='Enter all symbols of the alphabet, separated by commas (e.g., a,b,c)', max_length=255)),
                ('json_representation', models.JSONField(blank=True, help_text='JSON representation for graph visualization', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DFAState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_start', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('automaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.dfa')),
            ],
            options={
                'abstract': False,
                'unique_together': {('automaton', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DFATransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
                ('automaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='core.dfa')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transitions', to='core.dfastate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transitions', to='core.dfastate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alphabet', models.CharField(help_text='Enter all symbols of the alphabet, separated by commas (e.g., a,b,c)', max_length=255)),
                ('json_representation', models.JSONField(blank=True, help_text='JSON representation for graph visualization', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFAState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_start', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('automaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.nfa')),
            ],
            options={
                'abstract': False,
                'unique_together': {('automaton', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NFATransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
                ('automaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='core.nfa')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transitions', to='core.nfastate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transitions', to='core.nfastate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
