# Generated by Django 5.2.4 on 2025-07-16 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alphabet', models.CharField(help_text='Enter all symbols of the alphabet, separated by commas (e.g., a,b,c)', max_length=255)),
                ('json_representation', models.JSONField(blank=True, help_text='JSON representation for graph visualization', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_example', models.BooleanField(default=False, help_text='True if this is a system example automaton')),
                ('has_epsilon', models.BooleanField(default=False, help_text='True if this automaton has epsilon transitions')),
                ('cached_type', models.CharField(blank=True, help_text='Cached automaton type for performance', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_start', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('automaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.automaton')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('automaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='core.automaton')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transitions', to='core.state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transitions', to='core.state')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automaton_id', models.PositiveIntegerField()),
                ('automaton_name', models.CharField(max_length=255)),
                ('automaton_type', models.CharField(choices=[('DFA', 'DFA'), ('NFA', 'NFA')], max_length=10)),
                ('action', models.CharField(choices=[('create', 'Created'), ('view', 'Viewed'), ('edit', 'Edited'), ('simulate', 'Simulated'), ('minimize', 'Minimized'), ('convert', 'Converted'), ('delete', 'Deleted')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automata_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['automaton', 'is_start'], name='core_state_automat_f08a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['automaton', 'is_final'], name='core_state_automat_204137_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('automaton', 'name')},
        ),
        migrations.AddIndex(
            model_name='transition',
            index=models.Index(fields=['automaton', 'from_state'], name='core_transi_automat_e40a60_idx'),
        ),
        migrations.AddIndex(
            model_name='transition',
            index=models.Index(fields=['automaton', 'symbol'], name='core_transi_automat_10a796_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', '-timestamp'], name='core_userhi_user_id_4d6be7_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', 'action'], name='core_userhi_user_id_b8136f_idx'),
        ),
    ]
