# Generated by Django 5.2.4 on 2025-07-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dfastate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nfastate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dfatransition',
            name='symbol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nfatransition',
            name='symbol',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
