# Generated by Django 5.2.4 on 2025-07-15 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dfastate_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automaton_id', models.PositiveIntegerField()),
                ('automaton_name', models.CharField(max_length=255)),
                ('automaton_type', models.CharField(choices=[('DFA', 'DFA'), ('NFA', 'NFA')], max_length=10)),
                ('action', models.CharField(choices=[('create', 'Created'), ('view', 'Viewed'), ('edit', 'Edited'), ('simulate', 'Simulated'), ('minimize', 'Minimized'), ('convert', 'Converted'), ('delete', 'Deleted')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automata_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_userhi_user_id_4d6be7_idx'), models.Index(fields=['user', 'action'], name='core_userhi_user_id_b8136f_idx')],
            },
        ),
    ]
