# Generated by Django 5.2.4 on 2025-07-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfa',
            name='is_example',
            field=models.BooleanField(default=False, help_text='True if this is a system example automaton'),
        ),
        migrations.AddField(
            model_name='nfa',
            name='is_example',
            field=models.BooleanField(default=False, help_text='True if this is a system example automaton'),
        ),
    ]
